In [13]:
import os
import re
import numpy as np
import matplotlib.pyplot as plt
import netCDF4 as n
import glob
import xarray as xr
import seaborn as sns
import matplotlib.lines as mlines
import pandas as pd
import function_sampling_Thermal_forcing_files as fn
from matplotlib.colors import ListedColormap, BoundaryNorm
from scipy.stats import linregress

from collections import Counter
sns.set_context("paper")
sns.set_style("whitegrid")
computed_name = 'ComputedScalarsHelene'

#### Beware: deleted computed_shelfmelt_AIS_IMAU_UFEMISM1_expAE05.nc in ComputedScalarsHelene have orig_... and hb_calculated_now...

In [14]:
 
mnt_pth = '/Volumes/CrucialX8/computing/data/antarctica/' #mount path
pth_imip6hack= mnt_pth + 'ismip6_hackathon/ComputedScalars/' #write folder
pth_ismip6 =mnt_pth + 'ismip6_hackathon/' #read folder
pth_helene =mnt_pth + 'ismip6_hackathon/ComputedScalarsHelene/'
 
expnames = ['expAE02', 'expAE03', 'expAE04', 'expAE05']
removeFileID = [] # specify models to remove
 
metadata_file = 'Metadata.txt'
# Generate loop_info DataFrame

In [15]:
def get_model(string,exp):
    return string.split('/')[-1].split('AIS_')[-1].split('_'+str(exp))[0]
dic_area_of_interest = {}
dic_area_of_interest['FilchnerRonne'] = ['_sector_5','_sector_11']
dic_area_of_interest['Ross'] = ['_sector_2','_sector_6']
dic_area_of_interest['Amundsen'] = ['_sector_4']
y2sec=-365.25*24*3600
factor = y2sec/10**12

In [16]:
lst = glob.glob(pth_helene+f'expAE02/shelfmelt/*.nc')
lst.sort()

In [17]:
# avg and abs 2100
models=[]
paths =[]
exps =[]
for exp in expnames:
    lst = glob.glob(pth_helene+f'{exp}/shelfmelt/*.nc')
    lst.sort()
    #getting rid of old IMAU file (orig_...) and using the newly computed jb_computed... only:
    lst = lst[:-4]
    lst = lst[::-1]
    

    for name in lst:
        model = get_model(name,exp)
        if model in removeFileID:
            continue
        else:
            models.append(model)
            paths.append(name)
            exps.append(exp)
df = pd.DataFrame({ 'Experiment': exps,'Model': models, 'Path': paths}) 
for i in range(1,19):
    df['sector_'+str(i)]=0
for i in range(1,4):
    df['region_'+str(i)]=0
for key in dic_area_of_interest.keys():
    df[key]=0
df['AIS']=0
df2 = df.copy()
for i in range (df.shape[0]):
    pth_way = df.iloc[i].Path
    
    #get shelf area
    pth_area = pth_way.replace('shelfmelt','iareafl')
    
    # Melting
    d = xr.open_dataset(pth_way,decode_times=False )
    # Area
    d2 = xr.open_dataset(pth_area,decode_times=False )
    #
    ind = np.where(d.time.values <= 2100)
    
    
    
    tmin = np.min([d.time.size,d2.time.size])
    #melting per area
    y =d.shelfmelt.values[:tmin]* factor/d2.iareafl.values[:tmin] #T/m^3 yr
    yBMB =d.shelfmelt.values[:tmin]* factor
    
   
    yais =y[ind].mean()
    yaisBMB =yBMB[ind].cumsum()[-1]
    
    
    df['AIS'].iloc[i]=  yais
    df2['AIS'].iloc[i]=  yaisBMB
    

    for j in range(1,19):
        y =d['shelfmelt_sector_'+str(j)].values[:tmin]* factor/d2['iareafl_sector_'+str(j)].values[:tmin]  #GT/m^3 yr
        yBMB=d['shelfmelt_sector_'+str(j)].values[:tmin]* factor
        
        mnan = np.isnan(y)
        
        
       
        df['sector_'+str(j)].iloc[i] = y[ind].mean()
        df2['sector_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
    for j in range(1,4):
        y =d['shelfmelt_region_'+str(j)].values[:tmin]* factor/d2['iareafl_region_'+str(j)].values[:tmin]  #GT/m^3 yr
        yBMB=d['shelfmelt_region_'+str(j)].values[:tmin]* factor
        
        mnan = np.isnan(y)
        
        
       
        df['region_'+str(j)].iloc[i] = y[ind].mean()
        df2['region_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
        
    for key in dic_area_of_interest.keys():
        sectors = dic_area_of_interest[key].copy()
        ys = np.zeros((len(sectors),tmin))
        ysa = np.zeros((len(sectors),tmin))
        
        areas = np.zeros((len(sectors),tmin))
    
        for j,sector in enumerate(sectors):
            ys[j,:] = d[f'shelfmelt{sector}'].values[:tmin].copy()* factor
            areas[j,:] = d2[f'iareafl{sector}'].values[:tmin].copy()
            ysa[j,:]=ys[j,:]*areas[j,:]
        yBMB =  np.nansum(ys,axis = 0)
        y =  np.nansum(ys,axis = 0)/np.nansum(areas,axis= 0)
        df[key].iloc[i] = y[ind].mean()
        df2[key].iloc[i] = yBMB[ind].cumsum()[-1]
        
        
#         if (j==1 and i ==4):
#             print(d2['iareafl_sector_'+str(j)].values[:tmin])
#             break
# df.to_csv('tables/averegeshelfmelt_2100.csv', index=False)
df2.to_csv('tables/cumulative_shelfmelt_2100.csv', index=False)

/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AIS'].iloc[i]=  yais
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['AIS'].iloc[i]=  yaisBMB
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector_'+str(j)].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['sector_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:60: RuntimeWarning: invalid value encountered in divide
  y =d['shelfmelt_sector_'+str(j)].values[:tmin]* factor/d2['iareafl_sector_'+str(j)].values[:tmin]  #GT/m^3 yr
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region_'+str(j)].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['region_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:70: RuntimeWarning: invalid value encountered in divide
  y =d['shelfmelt_region_'+str(j)].values[:tmin]* factor/d2['iareafl_region_'+str(j)].values[:tmin]  #GT/m^3 yr
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:92: RuntimeWarning: invalid value encountered in divide
  y =  np.nansum(ys,axis = 0)/np.nansum(areas,axis= 0)
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[key].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:94: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[key].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3091885461.py:47: RuntimeWarning: invalid value encountered in divide
  y =d.shelfmelt.values[:tmin]* factor/d2.iareafl.values[:tmin] #T/m^3 yr

In [18]:
df2

,Experiment,Model,Path,sector_1,sector_2,sector_3,sector_4,sector_5,sector_6,sector_7,...,sector_16,sector_17,sector_18,region_1,region_2,region_3,FilchnerRonne,Ross,Amundsen,AIS
0,expAE02,IMAU_UFEMISM4,/Volumes/CrucialX8/computing/data/antarctica/i...,1611.824341,67816.421875,8278.105469,9334.640625,140990.515625,26225.423828,219.684067,...,1646.225708,3461.944580,0.000000,228031.484375,187076.406250,5108.169434,242537.779800,94041.856976,9334.641399,420216.031250
1,expAE02,IMAU_UFEMISM3,/Volumes/CrucialX8/computing/data/antarctica/i...,1891.794556,74746.570312,8521.494141,9050.348633,151186.796875,29280.572266,597.917725,...,1816.268311,4224.842285,4.919946,245397.062500,201505.343750,6046.030273,253945.894875,104027.149368,9050.347588,452948.437500
2,expAE02,IMAU_UFEMISM2,/Volumes/CrucialX8/computing/data/antarctica/i...,880.176331,73964.648438,3388.902100,3482.702148,144775.937500,28755.875000,195.901077,...,1432.764282,2647.808594,23.858397,226492.375000,177799.343750,4104.431641,247906.557846,102720.519241,3482.701520,408396.218750
3,expAE02,IMAU_UFEMISM1,/Volumes/CrucialX8/computing/data/antarctica/i...,974.645081,71335.101562,4468.673828,2365.238770,129208.289062,25799.421875,-0.000000,...,1411.865112,2671.535400,-0.000000,208351.921875,164163.296875,4083.401123,226168.220894,97134.514526,2365.238376,376598.718750
4,expAE02,VUW_PISM2_s4,/Volumes/CrucialX8/computing/data/antarctica/i...,11748.368164,62546.175781,17854.658203,21344.078125,211816.953125,37506.578125,6693.994629,...,2835.304688,5330.658203,14464.389648,325310.218750,360697.187500,22630.353516,373485.112577,100052.737001,21344.079353,708637.687500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,expAE05,IGE_ElmerIce,/Volumes/CrucialX8/computing/data/antarctica/i...,9006.089844,47834.742188,23822.015625,23822.710938,2710.322510,17403.414062,3779.043945,...,2500.085449,4152.203613,14909.415039,107195.890625,115427.257812,21561.705078,6885.203062,65238.163511,23822.707062,244184.859375
168,expAE05,DOE_MALI_8km_AntMean,/Volumes/CrucialX8/computing/data/antarctica/i...,9125.056641,55166.757812,23747.599609,29895.007812,9863.629883,18904.748047,2997.808105,...,227.771896,1344.373657,10883.929688,127798.078125,68881.773438,12456.077148,17337.025363,74071.517281,29895.011215,209135.937500
169,expAE05,DOE_MALI_8km_Ant95,/Volumes/CrucialX8/computing/data/antarctica/i...,9540.550781,63995.343750,24670.841797,32650.589844,10618.098633,21449.373047,3449.718994,...,268.997559,1334.802368,10738.963867,141475.421875,75720.351562,12342.761719,19004.323269,85444.713175,32650.591217,229538.562500
170,expAE05,DOE_MALI_4km,/Volumes/CrucialX8/computing/data/antarctica/i...,9402.107422,56845.140625,24807.822266,31764.996094,9940.785156,19144.416016,4943.729004,...,218.680893,1539.677490,11594.932617,132760.875000,73897.468750,13353.287109,17472.244884,75989.562393,31764.998978,220011.656250
171,expAE05,DC_ISSM,/Volumes/CrucialX8/computing/data/antarctica/i...,9044.494141,40034.347656,13615.262695,18936.585938,5208.791504,16158.004883,2603.946045,...,231.374588,856.377319,10709.779297,86839.492188,55562.933594,11797.534180,9811.070771,56192.358536,18936.591179,154199.953125

In [19]:
# avg and abs 2200
models=[]
paths =[]
exps =[]
for exp in expnames:
    lst = glob.glob(pth_helene+f'{exp}/shelfmelt/*.nc')
    lst.sort()    
    #getting rid of old IMAU file (orig_...) and using the newly computed jb_computed... only:
    lst = lst[:-4]
    lst = lst[::-1]
    

    for name in lst:
        model = get_model(name,exp)
        if model in removeFileID:
            continue
        else:
            models.append(model)
            paths.append(name)
            exps.append(exp)
df = pd.DataFrame({ 'Experiment': exps,'Model': models, 'Path': paths}) 
for i in range(1,19):
    df['sector_'+str(i)]=0
for i in range(1,4):
    df['region_'+str(i)]=0
for key in dic_area_of_interest.keys():
    df[key]=0
df['AIS']=0
df2 = df.copy()
for i in range (df.shape[0]):
    pth_way = df.iloc[i].Path
    #get shelf area
    pth_area = f'{pth_helene}/{df.iloc[i].Experiment}/iareafl/computed_iareafl_AIS_{df.iloc[i].Model}_{df.iloc[i].Experiment}.nc'
    
    # Melting
    d = xr.open_dataset(pth_way,decode_times=False )
    # Area
    d2 = xr.open_dataset(pth_area,decode_times=False )
    #
    ind = np.where(d.time.values <= 2200)
    
    
    
    tmin = np.min([d.time.size,d2.time.size])
    #melting per area
    y =d.shelfmelt.values[:tmin]* factor/d2.iareafl.values[:tmin] #T/m^3 yr
    yBMB =d.shelfmelt.values[:tmin]* factor
    
   
    yais =y[ind].mean()
    yaisBMB =yBMB[ind].cumsum()[-1]
    
    
    df['AIS'].iloc[i]=  yais
    df2['AIS'].iloc[i]=  yaisBMB
    

    for j in range(1,19):
        y =d['shelfmelt_sector_'+str(j)].values[:tmin]* factor/d2['iareafl_sector_'+str(j)].values[:tmin]  #GT/m^3 yr
        yBMB=d['shelfmelt_sector_'+str(j)].values[:tmin]* factor
        
        mnan = np.isnan(y)
        
        
       
        df['sector_'+str(j)].iloc[i] = y[ind].mean()
        df2['sector_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
    for j in range(1,4):
        y =d['shelfmelt_region_'+str(j)].values[:tmin]* factor/d2['iareafl_region_'+str(j)].values[:tmin]  #GT/m^3 yr
        yBMB=d['shelfmelt_region_'+str(j)].values[:tmin]* factor
        
        mnan = np.isnan(y)
        
        
       
        df['region_'+str(j)].iloc[i] = y[ind].mean()
        df2['region_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
        
    for key in dic_area_of_interest.keys():
        sectors = dic_area_of_interest[key].copy()
        ys = np.zeros((len(sectors),tmin))
        ysa = np.zeros((len(sectors),tmin))
        
        areas = np.zeros((len(sectors),tmin))
    
        for j,sector in enumerate(sectors):
            ys[j,:] = d[f'shelfmelt{sector}'].values[:tmin].copy()* factor
            areas[j,:] = d2[f'iareafl{sector}'].values[:tmin].copy()
            ysa[j,:]=ys[j,:]*areas[j,:]
        yBMB =  np.nansum(ys,axis = 0)
        y =  np.nansum(ys,axis = 0)/np.nansum(areas,axis= 0)
        df[key].iloc[i] = y[ind].mean()
        df2[key].iloc[i] = yBMB[ind].cumsum()[-1]
        
        
#         if (j==1 and i ==4):
#             print(d2['iareafl_sector_'+str(j)].values[:tmin])
#             break
# df.to_csv('tables/averegeshelfmelt_2100.csv', index=False)
df2.to_csv('tables/cumulative_shelfmelt_2200.csv', index=False)

/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AIS'].iloc[i]=  yais
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['AIS'].iloc[i]=  yaisBMB
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector_'+str(j)].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['sector_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region_'+str(j)].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['region_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[key].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[key].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:59: RuntimeWarning: invalid value encountered in divide
  y =d['shelfmelt_sector_'+str(j)].values[:tmin]* factor/d2['iareafl_sector_'+str(j)].values[:tmin]  #GT/m^3 yr
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:69: RuntimeWarning: invalid value encountered in divide
  y =d['shelfmelt_region_'+str(j)].values[:tmin]* factor/d2['iareafl_region_'+str(j)].values[:tmin]  #GT/m^3 yr
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3255398805.py:91: RuntimeWarning: invalid value encountered in divide
  y =  np.nansum(ys,axis = 0)/np.nansum(areas,axis= 0)

In [25]:
# avg and abs 2300
models=[]
paths =[]
exps =[]
for exp in expnames:
    lst = glob.glob(pth_helene+f'{exp}/shelfmelt/*.nc')
    lst.sort()
    #getting rid of old IMAU file (orig_...) and using the newly computed jb_computed... only:
    lst = lst[:-4]
    lst = lst[::-1]

    for name in lst:
        model = get_model(name,exp)
        if model in removeFileID:
            continue
        else:
            models.append(model)
            paths.append(name)
            exps.append(exp)
df = pd.DataFrame({ 'Experiment': exps,'Model': models, 'Path': paths}) 
for i in range(1,19):
    df['sector_'+str(i)]=0
for i in range(1,4):
    df['region_'+str(i)]=0
for key in dic_area_of_interest.keys():
    df[key]=0
df['AIS']=0
df2 = df.copy()
for i in range (df.shape[0]):
    pth_way = df.iloc[i].Path
    #get shelf area
    pth_area = f'{pth_helene}/{df.iloc[i].Experiment}/iareafl/computed_iareafl_AIS_{df.iloc[i].Model}_{df.iloc[i].Experiment}.nc'
    
    # Melting
    d = xr.open_dataset(pth_way,decode_times=False )
    # Area
    d2 = xr.open_dataset(pth_area,decode_times=False )
    #
    ind = np.where(d.time.values <= 2300)
    
    
    
    tmin = np.min([d.time.size,d2.time.size])
    #melting per area
    y =d.shelfmelt.values[:tmin]* factor/d2.iareafl.values[:tmin] #T/m^3 yr
    yBMB =d.shelfmelt.values[:tmin]* factor
    
   
    yais =y[ind].mean()
    yaisBMB =yBMB[ind].cumsum()[-1]
    
    
    df['AIS'].iloc[i]=  yais
    df2['AIS'].iloc[i]=  yaisBMB
    

    for j in range(1,19):
        y =d['shelfmelt_sector_'+str(j)].values[:tmin]* factor/d2['iareafl_sector_'+str(j)].values[:tmin]  #GT/m^3 yr
        yBMB=d['shelfmelt_sector_'+str(j)].values[:tmin]* factor
        
        mnan = np.isnan(y)
        
        
       
        df['sector_'+str(j)].iloc[i] = y[ind].mean()
        df2['sector_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
    for j in range(1,4):
        y =d['shelfmelt_region_'+str(j)].values[:tmin]* factor/d2['iareafl_region_'+str(j)].values[:tmin]  #GT/m^3 yr
        yBMB=d['shelfmelt_region_'+str(j)].values[:tmin]* factor
        
        mnan = np.isnan(y)
        
        
       
        df['region_'+str(j)].iloc[i] = y[ind].mean()
        df2['region_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
        
    for key in dic_area_of_interest.keys():
        sectors = dic_area_of_interest[key].copy()
        ys = np.zeros((len(sectors),tmin))
        ysa = np.zeros((len(sectors),tmin))
        
        areas = np.zeros((len(sectors),tmin))
    
        for j,sector in enumerate(sectors):
            ys[j,:] = d[f'shelfmelt{sector}'].values[:tmin].copy()* factor
            areas[j,:] = d2[f'iareafl{sector}'].values[:tmin].copy()
            ysa[j,:]=ys[j,:]*areas[j,:]
        yBMB =  np.nansum(ys,axis = 0)
        y =  np.nansum(ys,axis = 0)/np.nansum(areas,axis= 0)
        df[key].iloc[i] = y[ind].mean()
        df2[key].iloc[i] = yBMB[ind].cumsum()[-1]
        
        
#         if (j==1 and i ==4):
#             print(d2['iareafl_sector_'+str(j)].values[:tmin])
#             break
# df.to_csv('tables/averegeshelfmelt_2100.csv', index=False)
df2.to_csv('tables/cumulative_shelfmelt_2300.csv', index=False)

/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AIS'].iloc[i]=  yais
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['AIS'].iloc[i]=  yaisBMB
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sector_'+str(j)].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['sector_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region_'+str(j)].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['region_'+str(j)].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[key].iloc[i] = y[ind].mean()
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[key].iloc[i] = yBMB[ind].cumsum()[-1]
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:58: RuntimeWarning: invalid value encountered in divide
  y =d['shelfmelt_sector_'+str(j)].values[:tmin]* factor/d2['iareafl_sector_'+str(j)].values[:tmin]  #GT/m^3 yr
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:68: RuntimeWarning: invalid value encountered in divide
  y =d['shelfmelt_region_'+str(j)].values[:tmin]* factor/d2['iareafl_region_'+str(j)].values[:tmin]  #GT/m^3 yr
/var/folders/ph/m61jd3r90t190p6qvbps3yqct2hr65/T/ipykernel_66386/3495047340.py:90: RuntimeWarning: invalid value encountered in divide
  y =  np.nansum(ys,axis = 0)/np.nansum(areas,axis= 0)

In [21]:
df_test= df2[df2.Experiment == 'expAE02']

In [23]:
df_test

,Experiment,Model,Path,sector_1,sector_2,sector_3,sector_4,sector_5,sector_6,sector_7,...,sector_16,sector_17,sector_18,region_1,region_2,region_3,FilchnerRonne,Ross,Amundsen,AIS
0,expAE02,IMAU_UFEMISM4,/Volumes/CrucialX8/computing/data/antarctica/i...,2745.033936,162937.468750,8291.433594,9929.442383,241587.953125,40228.941406,898.381775,...,1673.774658,3485.093506,0.000000,4.254914e+05,242475.640625,5158.866699,371857.825321,203166.458339,9929.441125,6.731260e+05
1,expAE02,IMAU_UFEMISM3,/Volumes/CrucialX8/computing/data/antarctica/i...,3078.729736,179971.656250,8531.175781,10589.115234,270359.406250,45792.753906,1250.393066,...,1839.054443,4236.963379,4.919946,4.725306e+05,278840.562500,6080.937500,418033.716595,225764.475348,10589.106896,7.574512e+05
2,expAE02,IMAU_UFEMISM2,/Volumes/CrucialX8/computing/data/antarctica/i...,880.176331,141574.093750,3388.902100,3490.639404,201610.578125,44358.929688,195.901077,...,1432.764282,2647.808594,23.858397,3.509443e+05,219460.906250,4104.431641,326852.024283,185933.005062,3490.638750,5.745096e+05
3,expAE02,IMAU_UFEMISM1,/Volumes/CrucialX8/computing/data/antarctica/i...,980.030762,122743.648438,4468.673828,2468.053955,177003.093750,37955.757812,-0.000000,...,1411.865112,2671.535400,430.405670,3.076633e+05,197946.250000,4513.806641,292486.539061,160699.433270,2468.053848,5.101237e+05
4,expAE02,VUW_PISM2_s4,/Volumes/CrucialX8/computing/data/antarctica/i...,58893.988281,272715.031250,78759.843750,301957.468750,654504.750000,48881.550781,35832.753906,...,4601.173340,7815.533691,64841.601562,1.366830e+06,830648.875000,77258.265625,941399.503599,321596.582266,301957.467262,2.274738e+06
5,expAE02,VUW_PISM2_s3,/Volumes/CrucialX8/computing/data/antarctica/i...,48071.070312,248205.578125,74845.484375,105287.312500,622808.687500,48590.250000,32538.830078,...,4799.101562,7825.639160,62899.832031,1.099218e+06,776325.687500,75524.601562,888369.582457,296795.858001,105287.318459,1.951068e+06
6,expAE02,VUW_PISM2_s2,/Volumes/CrucialX8/computing/data/antarctica/i...,56130.468750,246540.781250,73023.664062,106060.804688,628941.437500,49213.351562,32578.037109,...,4688.640137,8346.356445,64616.292969,1.110696e+06,752164.437500,77651.289062,897561.727003,295754.152902,106060.759361,1.940512e+06
7,expAE02,VUW_PISM2_s1,/Volumes/CrucialX8/computing/data/antarctica/i...,58103.027344,296220.531250,80455.484375,173632.203125,675637.875000,49289.648438,45024.835938,...,4395.391113,7557.734375,64985.996094,1.284050e+06,882118.562500,76939.109375,970062.271370,345510.211594,173632.240677,2.243106e+06
8,expAE02,VUW_PISM2,/Volumes/CrucialX8/computing/data/antarctica/i...,57438.007812,267509.343750,75581.710938,183229.843750,648727.562500,49058.437500,33633.093750,...,4608.660645,8144.552734,65088.472656,1.232486e+06,811350.312500,77841.718750,930157.855059,316567.732082,183229.849823,2.121679e+06
9,expAE02,VUW_PISM1_s4,/Volumes/CrucialX8/computing/data/antarctica/i...,49242.960938,235349.968750,78229.164062,95204.492188,566876.562500,47083.429688,34308.898438,...,3704.051270,8837.822266,59684.265625,1.024903e+06,741846.187500,72226.132812,818521.089092,282433.414315,95204.519936,1.838975e+06
10,expAE02,VUW_PISM1_s3,/Volumes/CrucialX8/computing/data/antarctica/i...,45810.171875,212183.218750,71921.398438,94972.460938,582589.437500,47445.699219,31273.710938,...,3789.462891,8899.461914,56947.820312,1.007477e+06,700281.875000,69636.742188,815030.524845,259628.941655,94972.449181,1.777395e+06
11,expAE02,VUW_PISM1_s2,/Volumes/CrucialX8/computing/data/antarctica/i...,44827.441406,214412.343750,72830.742188,83425.929688,589676.562500,47216.664062,29858.613281,...,4204.235352,9256.684570,55221.742188,1.005173e+06,676969.125000,68682.679688,829949.554604,261628.989155,83425.912041,1.750825e+06
12,expAE02,VUW_PISM1_s1,/Volumes/CrucialX8/computing/data/antarctica/i...,-732.077881,-979.177734,-704.898438,-1014.207275,-3780.078857,-719.555237,-299.972473,...,26.453060,-135.778564,-936.935974,-7.210440e+03,-11548.916016,-1046.261597,-6522.961913,-1698.733072,-1014.207253,-1.980562e+04
13,expAE02,VUW_PISM1,/Volumes/CrucialX8/computing/data/antarctica/i...,48731.078125,228561.828125,75005.125000,101655.093750,562356.812500,47212.035156,32660.537109,...,4005.009521,8784.857422,56962.062500,1.016310e+06,726773.437500,69751.945312,808734.727474,275773.842934,101655.084404,1.812836e+06
14,expAE02,VUB_AISMPALEO,/Volumes/CrucialX8/computing/data/antarctica/i...,1173.792725,221753.609375,5638.363281,700.085266,482201.500000,98749.679688,315.325287,...,4891.717773,9884.082031,55.042580,7.114671e+05,468669.781250,14830.850586,734850.267696,320503.333923,700.085283,1.194968e+06
15,expAE02,UTAS_ElmerIce,/Volumes/CrucialX8/computing/data/antarctica/i...,20330.000000,210384.875000,46242.210938,75739.101562,379957.375000,73621.164062,18053.414062,...,7292.880371,15716.608398,34950.988281,7.326539e+05,572791.812500,57960.488281,579038.942120,284005.994576,75739.100815,1.363407e+06
16,expAE02,UNN_Ua,/Volumes/CrucialX8/computing/data/antarctica/i...,15270.643555,186263.468750,39732.710938,233588.500000,337886.125000,63802.226562,7001.009277,...,3209.492432,8269.633789,9033.086914,8.127410e+05,451207.375000,20512.228516,515426.219732,250065.650934,233588.519699,1.284461e+06
17,expAE02,ULB_fETISh-KoriBU2,/Volumes/CrucialX8/computing/data/antarctica/i...,35556.234375,196982.140625,55553.007812,403525.656250,372328.281250,78715.054688,31899.267578,...,5715.035645,21092.146484,46198.414062,1.063946e+06,704389.187500,73005.601562,596160.193832,275697.155544,403525.734146,1.841340e+06
18,expAE02,ULB_fETISh-KoriBU1,/Volumes/CrucialX8/computing/data/antarctica/i...,43381.554688,47778.707031,51950.421875,145521.218750,168366.390625,15387.622070,50111.859375,...,8606.637695,24175.833984,53363.414062,4.569984e+05,563675.437500,86145.937500,296536.867103,63166.318223,145521.208984,1.106820e+06
19,expAE02,UCSD_ISSM,/Volumes/CrucialX8/computing/data/antarctica/i...,166474.875000,28707.064453,145352.281250,252169.484375,163657.375000,3586.363525,21087.638672,...,5442.714355,12346.134766,206285.421875,7.563613e+05,312561.562500,224074.281250,211065.728825,32293.424694,252169.479675,1.292998e+06
20,expAE02,UCM_Yelmo,/Volumes/CrucialX8/computing/data/antarctica/i...,12486.672852,110541.343750,42383.601562,45147.296875,315538.625000,63618.832031,23806.636719,...,3127.412109,7485.716797,11932.506836,5.260974e+05,500638.906250,22545.638672,505480.792435,174160.164160,45147.282661,1.049282e+06
21,expAE02,PIK_PISM,/Volumes/CrucialX8/computing/data/antarctica/i...,19384.744141,105470.734375,53946.242188,56284.261719,189704.937500,28032.519531,14284.582031,...,4337.618164,14319.758789,24743.332031,4.247911e+05,383256.937500,43400.718750,339675.473124,133503.272396,56284.264114,8.514487e+05
22,expAE02,NORCE_CISM5-MAR364-ERA-t1,/Volumes/CrucialX8/computing/data/antarctica/i...,25993.099609,180811.156250,53340.925781,95892.390625,346051.875000,70841.382812,21753.013672,...,13276.816406,20176.560547,40898.492188,7.020894e+05,625254.562500,74351.859375,564205.129681,251652.528301,95892.380501,1.401696e+06
23,expAE02,NORCE_CISM5-MAR364-ERA-t1-nonlocal,/Volumes/CrucialX8/computing/data/antarctica/i...,26121.902344,236601.296875,55420.523438,91438.750000,352505.468750,92453.843750,21275.046875,...,14027.587891,20111.806641,40419.957031,7.620881e+05,651339.375000,74559.343750,562637.865021,329055.061844,91438.725510,1.487987e+06
24,expAE02,NORCE_CISM5-MAR364-ERA-t1-local,/Volumes/CrucialX8/computing/data/antarctica/i...,25730.345703,237708.390625,54584.933594,81899.515625,372195.468750,82794.468750,21282.849609,...,13746.648438,19882.746094,38946.695312,7.721188e+05,631413.937500,72576.078125,589641.723831,320502.859173,81899.502769,1.476108e+06
25,expAE02,NORCE_CISM4-MAR364-JRA-t1,/Volumes/CrucialX8/computing/data/antarctica/i...,20950.402344,190525.250000,52499.003906,83636.914062,401860.375000,75026.664062,25587.328125,...,10931.573242,15750.917969,38958.906250,7.494718e+05,626207.562500,65641.367188,617717.047497,265551.926870,83636.896927,1.441321e+06
26,expAE02,NORCE_CISM4-MAR364-ERA-t1,/Volumes/CrucialX8/computing/data/antarctica/i...,21299.013672,194175.765625,52897.500000,83902.875000,386241.625000,76392.929688,25508.968750,...,10487.965820,14833.291992,37703.664062,7.385169e+05,621220.562500,63024.910156,597104.326660,270568.721739,83902.868774,1.422762e+06
27,expAE02,NORCE_CISM4-MAR364-ERA-t1-nonlocal,/Volumes/CrucialX8/computing/data/antarctica/i...,21823.357422,229918.890625,54360.976562,61712.675781,345528.781250,98801.156250,23805.837891,...,11201.619141,16416.447266,36870.554688,7.133451e+05,607771.312500,64488.632812,547037.836979,328720.034962,61712.681572,1.385604e+06
28,expAE02,NORCE_CISM4-MAR364-ERA-t1-local,/Volumes/CrucialX8/computing/data/antarctica/i...,21536.052734,235454.781250,55037.371094,65904.062500,374607.156250,90516.507812,23459.423828,...,11124.315430,17243.234375,35413.246094,7.525398e+05,600861.312500,63780.773438,578642.409840,325971.312702,65904.076691,1.417182e+06
29,expAE02,NORCE_CISM3-MAR364-ERA-t1,/Volumes/CrucialX8/computing/data/antarctica/i...,26255.031250,208258.265625,58282.996094,117212.453125,438618.812500,80078.867188,30603.867188,...,10446.481445,17762.351562,41302.429688,8.486277e+05,716527.750000,69511.226562,681815.706661,288337.150713,117212.463356,1.634666e+06
30,expAE02,NORCE_CISM3-MAR364-ERA-t1-nonlocal,/Volumes/CrucialX8/computing/data/antarctica/i...,23060.205078,234141.843750,52161.078125,53450.984375,351635.531250,96562.343750,13989.391602,...,11258.303711,19203.525391,40020.707031,7.144496e+05,586305.625000,70482.578125,562928.799236,330704.194267,53450.970909,1.371238e+06
31,expAE02,NORCE_CISM3-MAR364-ERA-t1-local,/Volumes/CrucialX8/computing/data/antarctica/i...,23464.070312,237310.015625,49479.988281,52402.417969,379879.093750,85968.445312,12260.293945,...,11082.551758,18871.000000,41010.269531,7.425351e+05,571629.250000,70963.796875,595884.194408,323278.425709,52402.427330,1.385128e+06
32,expAE02,NORCE_CISM2-MAR364-ERA-t1,/Volumes/CrucialX8/computing/data/antarctica/i...,27675.650391,215150.156250,66637.242188,99420.570312,490560.593750,87079.328125,28641.109375,...,11535.040039,19203.640625,49772.296875,8.994443e+05,782184.875000,80510.976562,752324.343407,302229.453948,99420.577185,1.762141e+06
33,expAE02,NCAR_CISM2,/Volumes/CrucialX8/computing/data/antarctica/i...,43345.921875,304246.687500,67396.687500,128437.796875,527687.062500,92841.195312,24277.451172,...,12663.591797,18677.525391,56965.429688,1.071113e+06,816252.812500,88306.523438,802014.416500,397087.911243,128437.803169,1.975673e+06
34,expAE02,NCAR_CISM1,/Volumes/CrucialX8/computing/data/antarctica/i...,26556.652344,219582.531250,55513.472656,49497.636719,385912.375000,92800.140625,12469.283203,...,9340.050781,16091.705078,47014.816406,7.370626e+05,588599.562500,72446.578125,607834.896147,312382.717486,49497.648632,1.398108e+06
35,expAE02,LSCE_GRISLI,/Volumes/CrucialX8/computing/data/antarctica/i...,13012.969727,296537.125000,23971.404297,113624.242188,323255.718750,39944.925781,9783.268555,...,2534.895508,5050.316895,16938.705078,7.704014e+05,363746.843750,24523.914062,462004.559093,336482.061229,113624.222836,1.158672e+06
36,expAE02,LSCE_GRISLI2,/Volumes/CrucialX8/computing/data/antarctica/i...,21821.605469,240907.078125,40466.164062,37434.343750,295027.437500,42800.621094,13873.474609,...,3333.728027,6076.334961,26011.003906,6.356570e+05,406475.781250,35421.085938,448020.076500,283707.713625,37434.340759,1.077554e+06
37,expAE02,ILTS_SICOPOLIS,/Volumes/CrucialX8/computing/data/antarctica/i...,38159.796875,400257.187500,57695.894531,256050.000000,571376.687500,78720.617188,39567.785156,...,5814.615234,13544.535156,41219.812500,1.323539e+06,900610.437500,60578.933594,864857.772636,478977.775849,256049.938812,2.284728e+06
38,expAE02,IGE_ElmerIce,/Volumes/CrucialX8/computing/data/antarctica/i...,20605.218750,133217.875000,47215.300781,68820.320312,294875.718750,41174.671875,30240.525391,...,7274.707031,13664.770508,36790.996094,5.647342e+05,552454.687500,57730.468750,462713.110249,174392.516596,68820.360016,1.174919e+06
39,expAE02,DOE_MALI_8km_AntMean,/Volumes/CrucialX8/computing/data/antarctica/i...,20256.283203,270993.468750,51282.066406,526648.812500,450845.187500,79818.609375,28426.669922,...,4720.016602,11496.541016,30985.146484,1.320026e+06,684622.062500,47201.718750,685139.821247,350812.071259,526648.923264,2.051850e+06
40,expAE02,DOE_MALI_8km_Ant95,/Volumes/CrucialX8/computing/data/antarctica/i...,21022.947266,314642.750000,50618.675781,654499.937500,472613.562500,80233.921875,44077.710938,...,4896.090820,11407.310547,30322.203125,1.513398e+06,712376.687500,46625.601562,713731.174686,394876.673967,654499.783340,2.272400e+06
41,expAE02,DOE_MALI_4km,/Volumes/CrucialX8/computing/data/antarctica/i...,19622.791016,263453.781250,48271.113281,321624.250000,460893.218750,81648.937500,40088.609375,...,5714.145020,12550.206055,33146.929688,1.113865e+06,702311.125000,51411.273438,694012.715122,345102.750245,321624.176163,1.867588e+06
42,expAE02,DC_ISSM,/Volumes/CrucialX8/computing/data/antarctica/i...,31128.771484,206959.312500,48533.351562,97540.773438,373823.843750,80370.359375,23742.830078,...,7579.209961,12807.190430,43903.007812,7.579861e+05,692973.625000,64289.406250,588108.934179,287329.698416,97540.733658,1.515250e+06